In [1]:
from sklearn.metrics.pairwise import pairwise_distances
import numpy as np

In [8]:
X = np.array([[1,1,1],[2,2,2],[3,3,3]])
Y = np.array([1,1,1]).reshape(1, -1)

In [9]:
pairwise_distances(X)

array([[0.        , 1.73205081, 3.46410162],
       [1.73205081, 0.        , 1.73205081],
       [3.46410162, 1.73205081, 0.        ]])

In [10]:
pairwise_distances(X,Y)

array([[0.        ],
       [1.73205081],
       [3.46410162]])

In [11]:
B = np.array([[1,2,3],[1,2,3]])
B.shape

(2, 3)

In [12]:
arr = np.array([23, 12, 1, 3, 4, 5, 6])
print("The Original Array Content")
print(arr)
  
# value of k
k = 4
  
# using np.argpartition()
result = np.argpartition(arr, k)
result

The Original Array Content
[23 12  1  3  4  5  6]


array([4, 3, 2, 5, 6, 1, 0], dtype=int64)

In [23]:
nearest_label = np.array([[1,1,2],[3,3,4]])

In [24]:
np.unique(nearest_label, axis=1)[:,0]

array([1, 3])

In [25]:
from sklearn.utils.multiclass import check_classification_targets

In [26]:
check_classification_targets?

Signature: check_classification_targets(y)
Docstring:
Ensure that target y is of a non-regression type.

Only the following target types (as defined in type_of_target) are allowed:
    'binary', 'multiclass', 'multiclass-multioutput',
    'multilabel-indicator', 'multilabel-sequences'

Parameters
----------
y : array-like
    Target values.
File:      c:\users\annie\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages\sklearn\utils\multiclass.py
Type:      function
