In [1]:
from sklearn.metrics.pairwise import pairwise_distances
import numpy as np

In [8]:
X = np.array([[1,1,1],[2,2,2],[3,3,3]])
Y = np.array([1,1,1]).reshape(1, -1)

In [9]:
pairwise_distances(X)

array([[0.        , 1.73205081, 3.46410162],
       [1.73205081, 0.        , 1.73205081],
       [3.46410162, 1.73205081, 0.        ]])

In [10]:
pairwise_distances(X,Y)

array([[0.        ],
       [1.73205081],
       [3.46410162]])

In [11]:
B = np.array([[1,2,3],[1,2,3]])
B.shape

(2, 3)

In [12]:
arr = np.array([23, 12, 1, 3, 4, 5, 6])
print("The Original Array Content")
print(arr)
  
# value of k
k = 4
  
# using np.argpartition()
result = np.argpartition(arr, k)
result

The Original Array Content
[23 12  1  3  4  5  6]


array([4, 3, 2, 5, 6, 1, 0], dtype=int64)

In [23]:
nearest_label = np.array([[1,1,2],[3,3,4]])

In [24]:
np.unique(nearest_label, axis=1)[:,0]

array([1, 3])

In [25]:
from sklearn.utils.multiclass import check_classification_targets

In [26]:
check_classification_targets?

Signature: check_classification_targets(y)
Docstring:
Ensure that target y is of a non-regression type.

Only the following target types (as defined in type_of_target) are allowed:
    'binary', 'multiclass', 'multiclass-multioutput',
    'multilabel-indicator', 'multilabel-sequences'

Parameters
----------
y : array-like
    Target values.
File:      c:\users\annie\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages\sklearn\utils\multiclass.py
Type:      function


In [3]:
y_pred = np.array([1,0,1,0,1])
y = np.array([1,1,1,0,1])

In [2]:
import numpy as np

In [6]:
(y_pred == y)

array([ True, False,  True,  True,  True])

In [7]:
score = 0
for i in range(len(y)):
    if y[i] == y_pred[i]:
        score += 1
score/len(y)

0.8

In [6]:
import numpy as np
import pandas as pd
from numpy.testing import assert_array_equal

from sklearn.utils.estimator_checks import check_estimator
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier

from sklearn_questions import KNearestNeighbors
from sklearn_questions import MonthlySplit

In [7]:
X, y = make_classification(n_samples=200, n_features=20,
                               random_state=42)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [10]:
knn = KNeighborsClassifier(n_neighbors=3)
y_pred_sk = knn.fit(X_train, y_train).predict(X_test)

In [11]:
X_train.shape

(150, 20)

In [12]:
y_train.shape

(150,)

In [13]:
y_pred_sk

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0])

In [15]:
from sklearn.metrics.pairwise import pairwise_distances

In [42]:
distances = pairwise_distances(X_test, X_train)
nearest_indexes = np.argsort(distances)
k_nearest_indexes = nearest_indexes[:, :3]
# most seen labels
k_nearest_label = y_train[k_nearest_indexes]
y_pred = [np.unique(K)[0] for K in k_nearest_label] 
y_pred

[0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0]

In [46]:
np.unique?

Signature:
np.unique(
    ar,
    return_index=False,
    return_inverse=False,
    return_counts=False,
    axis=None,
    *,
    equal_nan=True,
)
Docstring:
Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional
outputs in addition to the unique elements:

* the indices of the input array that give the unique values
* the indices of the unique array that reconstruct the input array
* the number of times each unique value comes up in the input array

Parameters
----------
ar : array_like
    Input array. Unless `axis` is specified, this will be flattened if it
    is not already 1-D.
return_index : bool, optional
    If True, also return the indices of `ar` (along the specified axis,
    if provided, or in the flattened array) that result in the unique array.
return_inverse : bool, optional
    If True, also return the indices of the unique array (for the specified
    axis, if provided) that can be used to reconstruct `ar`.
re

In [45]:
np.array(y_pred) == y_pred_sk

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True, False,  True, False,  True,  True, False,
       False,  True,  True,  True, False,  True,  True, False,  True,
       False, False,  True,  True, False,  True, False, False,  True,
       False,  True,  True,  True,  True, False, False,  True, False,
        True,  True,  True,  True,  True])

In [20]:
np.argsort?

Signature: np.argsort(a, axis=-1, kind=None, order=None)
Docstring:
Returns the indices that would sort an array.

Perform an indirect sort along the given axis using the algorithm specified
by the `kind` keyword. It returns an array of indices of the same shape as
`a` that index data along the given axis in sorted order.

Parameters
----------
a : array_like
    Array to sort.
axis : int or None, optional
    Axis along which to sort.  The default is -1 (the last axis). If None,
    the flattened array is used.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort under the covers and, in general, the
    actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.
order : str or list of str, optional
    When `a` is an array with fields define

In [3]:
X_train = np.array([[1,1,1,1]])

NameError: name 'np' is not defined

In [5]:
np.unique?

Signature:
np.unique(
    ar,
    return_index=False,
    return_inverse=False,
    return_counts=False,
    axis=None,
    *,
    equal_nan=True,
)
Docstring:
Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional
outputs in addition to the unique elements:

* the indices of the input array that give the unique values
* the indices of the unique array that reconstruct the input array
* the number of times each unique value comes up in the input array

Parameters
----------
ar : array_like
    Input array. Unless `axis` is specified, this will be flattened if it
    is not already 1-D.
return_index : bool, optional
    If True, also return the indices of `ar` (along the specified axis,
    if provided, or in the flattened array) that result in the unique array.
return_inverse : bool, optional
    If True, also return the indices of the unique array (for the specified
    axis, if provided) that can be used to reconstruct `ar`.
re

In [4]:
import numpy as np